version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - ls -lrt
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pylint
      - pip install pipenv
      - pip install bandit
      - pylint --ignore=myproject,.ebextensions,__pycache__,static,staticfiles,templates,.gitignore,buidspec.yml,db.sqlite3 --generate-rcfile > .pylintrc
      - sed -i 's/fail-under=10/fail-under=2/g'  .pylintrc
  pre_build:
    commands:
    - python --version
  build:
    commands:
      - pylint -rn myapp/* --disable=all
      - bandit -iii -r myproject --exclude=buildspec.yml,db.sqlite3,requirements.txt
      - pipenv requirements
      - pipenv check 
      - pipenv check > pipenv-output.txt

artifacts:
 files:
  - '**/*'
   
